defaults:
  - dset: debug
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

# Dataset related
sample_rate: 16000
segment: 4
stride: 1    # in seconds, how much to stride between training examples
pad: true   # if training sample is too short, pad it

# Dataset Augmentation
remix: true   # remix noise and clean
bandmask: 1.   # drop at most this fraction of freqs in mel scale
shift: 1    # random shift, number of samples
shift_same: true   # shift noise and clean by the same amount
revecho: 1  # add reverb like augment

# Logging and printing, and does not impact training
num_prints: 5
device: local
num_workers: 5
verbose: 1
show: 1   # just show the model and its size and exit

# Checkpointing, by default automatically load last checkpoint
checkpoint: true
continue_from: '' # Path the a checkpoint.th file to start from.
                  # this is not used in the name of the experiment!
                  # so use a dummy=something not to mixup experiments.
continue_best: true  # continue from best, not last state if continue_from is set.
continue_pretrained:   # use either dns48, dns64 or master64 to fine tune from pretrained-model
restart: true # Ignore existing checkpoints
checkpoint_file: checkpoint.th
best_file: best.th  # will contain only best model at any point
history_file: history.json
samples_dir: samples
save_again: false  # if true, only load checkpoint and save again, useful to reexport best.th

# Other stuff
dummy:  # use this if you want twice the same exp, with a different name

# Evaluation stuff
pesq: false # compute pesq?
eval_every: 10  # compute test metrics every so epochs
dry: 0.  # dry/wet knob value at eval
streaming: true  # use streaming evaluation for Demucs

# Optimization related
optim: null
lr: 0
beta2: 0.999
loss: 0
stft_loss: true
stft_sc_factor: .5
stft_mag_factor: .5
epochs: 500
batch_size: 64

# Models
model: dwave # either demucs or dwave
demucs:
  chin: 1
  chout: 1
  hidden: 48
  max_hidden: 10000
  causal: false
  glu: false
  depth: 5
  kernel_size: 8
  stride: 4
  normalize: true
  resample: 4
  growth: 2
  rescale: 0.1

# Experiment launching, distributed
ddp: true
ddp_backend: nccl
rendezvous_file: ./rendezvous

# Internal config, don't set manually
rank:
world_size:

# Hydra config
hydra:
  run:
    dir: ./outputs/exp_${hydra.job.override_dirname}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test', 'dset.noisy_json', 'dset.noisy_dir',
          'num_prints', 'continue_from', 'save_again',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        
      console:
        

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr
